FROM ocaml/opam:ubuntu

RUN sudo apt-get update && sudo apt-get install -y \
        build-essential \
        libcap-ng-dev \
        libnl-3-dev \
        libnl-route-3-dev \
        linux-libc-dev \
        qemu-system-x86 \
        pkg-config 

ADD ./src /home/opam/runner
RUN sudo chown -R opam:opam /home/opam/runner

USER opam
WORKDIR /home/opam/runner
RUN make

VOLUME /src
WORKDIR /src

ENTRYPOINT [ "sudo", "/home/opam/runner/runner" ]
